### ISSUE TITLE
on funding reuse, Bob never creates Lock transaction

### ISSUE THREAD

**Issue by Lederstrumpf** [farcaster-project/farcaster-node#152]
if you abort a swap post-funding and then restart with reuse of the funding address, on the subsequent attempt, it won't move to `Lock`. This appears to be due to a race condition:
1. When swapd receives `FundingUpdated`, [it checks whether the pending request already exists](https://github.com/farcaster-project/farcaster-node/blob/main/src/swapd/runtime.rs#L1202-L1204)
2. the pending request is [only added](https://github.com/farcaster-project/farcaster-node/blob/main/src/swapd/runtime.rs#L741-L749) after `Msg::Reveal(Reveal::Proof(_))` has been received.

Solution: syncer should correctly ignore funding txs that were created prior to it being instantiated.

**Comment by zkao** [comment]
there is an option on the syncer, for the earliest block to be greater than some block, and its passed, but the syncer seems to ignore it @TheCharlatan

**Comment by TheCharlatan** [comment]
I just added the option today in monero-rpc-rs to select transfer by block height. Am patching the code now to make use of it. Will then work on something similar for Bitcoin as well.

**Comment by zkao** [comment]
reminder: on swapd there is some lookback weirdness i added at some point that probably should be removed after @TheCharlatan completes his work

**Comment by TheCharlatan** [comment]
As of #167 , the height argument for the WatchAddress task is now respected. I also opened #174 to save the counter to the node secrets file. This way, we won't derive the same address twice. #174 needs more follow-up work though, to increment only where appropriate.
