### ISSUE TITLE
Wallet printing wrong private keys

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#157]
On `Request::Tx(Tx::Buy(buy_tx))` and `Request::Tx(Tx::Refund(refund_tx))` implementation in walletd the private view key is not correct, only one share is used.

[here](https://github.com/farcaster-project/farcaster-node/blob/main/src/walletd/runtime.rs#L1119-L1126) only alice share is used, same only with bob in the other impl:
```
let view_key = *alice_params
    .accordant_shared_keys
    .clone()
    .into_iter()
    .find(|vk| vk.tag() == &SharedKeyId::new(SHARED_VIEW_KEY_ID))
    .unwrap()
    .elem();
info!("Full secret monero view key: {}", view_key);
```

The key manager can be used to derive the private view key share and the print `view_key + {own_share}`.

**Comment by TheCharlatan** [comment]
Addressed in https://github.com/farcaster-project/farcaster-node/pull/158
