### ISSUE TITLE
Format SwapId when running `swap-cli ls`

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#183]
The SwapId is currently returned as:

```
swap_list(---
- - 110
  - 202
  - 178
  - 71
  - 171
  - 91
  - 126
  - 20
  - 114
  - 174
  - 82
  - 254
  - 207
  - 58
  - 155
  - 142
  - 201
  - 42
  - 94
  - 92
  - 27
  - 126
  - 135
  - 85
  - 145
  - 207
  - 73
  - 95
  - 57
  - 7
  - 151
  - 30
)
```

In the `info` call it is truncated: 
```
swaps:
  - "0x6eca…971e"
 ```
 
 And the `take` success message is also truncated:
```
Success: Public offer registered: 0x6010…30c4
 ```
If I'm not  mistaken the only way to retrieve a SwapId currently is by copying it from the logs. The SwapId should always be printed in full.

**Comment by h4sh3d** [comment]
This is related to core impl. The macro used that generates Display truncate the id, this has to be fixed in core.

**Comment by h4sh3d** [comment]
Working on different displays (cli, logs).

This one is related to the yaml serialization: the `SwapId` struct is an array of 32-bytes, yaml will serialize through `serde` the content of this struct, i.e. a list of bytes. Exploring the best way to apply the format we want where we want it.

**Comment by h4sh3d** [comment]
To resolve the `info` command formating, after landing the PR in core and update the node we just have to remove:
```
#[serde_as(as = "Vec<DisplayFromStr>")]
```
So serde is used with its default.
