### ISSUE TITLE
SweepSuccess: use that to finalize Bob's side

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#195]
this event is not reliably being emitted, although the sweep is actually successfull

**Comment by zkao** [comment]
it may be important to get this to work correctly, because its the best trigger for finalizing the swap, @TheCharlatan 

around the time such a log is produced a sweep success event could be sent?

```
[2021-11-18T19:20:47Z INFO  farcaster_node::syncerd::monero_syncer] sweep transaction hash 7ef95f20a773c6319d46f829142a6090374ef1592a7ae3446df0cc2e84be68bd
```

**Comment by TheCharlatan** [comment]
As far as I can tell, the SweepSuccess message is sent correctly. I tested it on a couple of swaps and always saw it on the logs.
