### ISSUE TITLE
Syncerd: drop all task from a swapd "source" when swap complete

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#196]
Is there any functionality in the syncer like that? @TheCharlatan

**Comment by TheCharlatan** [comment]
Not yet, but should be fairly straight forward to add, all the information to enable this is already cached.

**Comment by TheCharlatan** [comment]
Added ability to abort all tasks in the syncer from the same source id with https://github.com/farcaster-project/farcaster-node/pull/198 .
