### ISSUE TITLE
Call to `transaction_get_raw` produce warnings

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#212]
@TheCharlatan is this warning from electrum normal?

```
 [2021-11-20T10:24:21Z WARN  electrum_client::client] call 'transaction_get_raw' failed with EOF while parsing a value at line 1 column 0, retry: 1/1
```

**Comment by TheCharlatan** [comment]
I would expect this to happen sometimes. Does it happen all the time going by what you see from the logs? I will soften the load on the electrum servers a bit soon.

**Comment by h4sh3d** [comment]
Not everytime, and it looks like it is not a problem. Labeling it as `wontfix` but keep it open for now for documentation purposes.
