### ISSUE TITLE
Exit syncer upon farcasterd request

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#217]
farcasterd knows when a syncer is not needed anymore, and thus can ask the syncer to quit

**Comment by zkao** [comment]
https://github.com/farcaster-project/farcaster-node/pull/215/files#diff-f9b44691006c3b3f6c584bbfd76254d3be7ae0a5ebc46567dd9370b6912bc613R227

**Comment by TheCharlatan** [comment]
Is there an rpc request that farcasterd can issue to terminate other daemons?

**Comment by zkao** [comment]
Not yet, make it Kill or Terminate so that we have some killer or terminator code
