### ISSUE TITLE
deadlock on funding too early for bob

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#225]

**Comment by TheCharlatan** [comment]
This is done now, right @zkao?

**Comment by zkao** [comment]
not really, what is fixed is the timing for sending the progress reports from swapd.

missing:
- [ ] remove the printed messages from walletd asking for funding, 
- [ ] improve the state management, so that it doesnt get into a deadlock if funding was updated at the wrong state

**Comment by TheCharlatan** [comment]
The remaining bullet points were addressed.
