### ISSUE TITLE
log should distinguish different swapds

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#257]
```
2021-11-29T13:06:30Z INFO  farcaster_node::swapd::runtime] Terminating swap<0x7c29d85b9626425b9902e0f9bc5f49387f8b53e46d0df650ea511eae04a98077
```

**Comment by zkao** [comment]
@h4sh3d, for debugging all things that went wrong on the reddit tests, it would be important to distinguish all the different swaps at the log level

any interest in looking at this?

**Comment by zkao** [comment]
farcaster_node::swapd::runtime -> farcaster_node::swapd<0x7c29..8077>::runtime

**Comment by h4sh3d** [comment]
I don't know if `log` allows that but I was implementing `swapd::runtime: <short_id> | ...`

**Comment by h4sh3d** [comment]
Linked to #170
