### ISSUE TITLE
unstoppableswap gui

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#258]
requested feedback for data to stateful clients here:

https://github.com/UnstoppableSwap/unstoppableswap-gui/issues/31#issue-1066049430

**Comment by zkao** [comment]
their response:

> Thanks for reaching out! I must admit that I am not very familiar with your architecture yet, but I will try to read the RFCs as soon as I have some time. The basic things needed to make forecaster compatible with this GUI are:
> 
>     Ability to retrieve information about swaps that have occurred/been started in the past. Either by having a database that is easily accessible through software stacks other than Rust (Comit uses a sqlite database), or by having some sort of API/RPC that we can call to get this information. We need to be able to derive some basic information about the swap from this data (exchange rate, amounts, fees, etc.). We also need to know what state the swap is in and what actions the user can take (resume, cancel, refund, ...).
>     Ability to start/resume/cancel a swap either by starting the binary in non-interactive mode or by calling an API/RPC.
>     Ability to receive status updates for a running swap. Either by having the binary pipe logs to stdout/stderr in a format we can work with ( e.g. JSON) or by registering somewhere to send updates to the GUI (e.g. zeromq).
>     Ability to interact with internal wallet. If Farcaster has an internal wallet that the user should have access to, we need a way to query the current balance and withdraw money from that wallet.
>

**Comment by zkao** [comment]
related to #285

**Comment by zkao** [comment]
related to #274 and #399

**Comment by zkao** [comment]
and #194

**Comment by TheCharlatan** [comment]
I took took the liberty to compile a list of things to be done from the message to make it easier to parse:

- [ ]  Ability to retrieve information about swaps that have occurred/been started in the past. 
- [ ] Get basic information on a running swap, like its exchange rate, amounts, fees, etc.
- [x] Track the state of a swap
- [x] Track what actions the user can take in the current swap (partially fullfilled, needs a cleaner interface)
- [x] Ability to start a swap
- [ ] Ability to cancel a swap
- [ ] Ability to resume a swap (restore it to a previous state)
- [x] Ability to receive status updates for a running swap

**Comment by TheCharlatan** [comment]
We're now building out our own GUI in https://github.com/farcaster-project/farcaster-gui . Integration with unstoppable swaps GUI is shelved for now, since the discrepancies between their current workflow tailored to the comit xmr-btc-swap software are too big to re conciliate.
