### ISSUE TITLE
Difference between `tests/rpc` and `tests/fuctional-swap`

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#260]
While modifying the way we launch syncers and where farcasterd finds its config arguments, I modified the `tests/rpc`. It is now very close to `tests/functional-swap` and we are not sure what the `rpc` tests are about.

@Lederstrumpf what was the first intention behind rpc tests?

**Comment by TheCharlatan** [comment]
Closing this. The rpc tests are useful to me as a sanity check that does not require any external services.
