### ISSUE TITLE
Calling progress on unconnected or non-existing swap does not terminate

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#272]
Calling `progress <SWAP_ID>` on an unconnected swap or a non-existing <SWAP_ID> does not return. On a non-existing <SWAP_ID> progress should be returning an error, while on an unconnected swap, I would expect the first message in the usual progress flow to be printed, e.g.: `Proposing to the Maker that I take the swap offer with id 0xe46c…84ba`. I would also suggest to add another message once the swap is connected.

**Comment by h4sh3d** [comment]
Is there an "unconnected swap"? In my understanding the offer become a swap only when a taker arrives, so swap is non-existant or connected. Is that correct @zkao?

**Comment by zkao** [comment]
im working on this

**Comment by zkao** [comment]
> Is there an "unconnected swap"? In my understanding the offer become a swap only when a taker arrives, so swap is non-existant or connected. Is that correct @zkao?

makers swapd is only launched after taker show up

**Comment by zkao** [comment]
unconnected swap are on farcasterd Runtime as:
        making_swaps
        taking_swaps

**Comment by TheCharlatan** [comment]
Closed by #280
