### ISSUE TITLE
Standardize progress funding message

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#273]
On the `progress_report3` branch (#259) the funding messages are still inconsistent:
Bob funding:
`Success: Funding address: tb1qw9aggkkydncyjcda28628dgcp6jhvmzay0thzj`
Alice funding:
`Success: Alice, please send 0.001000000000 XMR to 56FuFfbfbdP6YjhTjYVaCRCD9HKQGipmtLgnZ5cbRRAu7F33UkEjKhYgzSSNRJvz5wXtzZ3d3EVs1W6uxdzL5WVqSVsHT46`

**Comment by zkao** [comment]
im trying to achieve this here #278

**Comment by h4sh3d** [comment]
The report progress will print all line, with the last one prefixed by "Success: ".

In https://github.com/farcaster-project/farcaster-node/issues/274 the proposition for displaying funding required would be:
```
Funding required: send 0.001000000000 XMR to 55GAd9ddNjKRAyi74PwhTKXkhyfDwvVmTGh7NTNHsaA2BfwShd5v8VHPWJaKuKNJYFJwvEx5nZ6fiMr4BC6UkoPzHjryVNK

or 

Success: Funding required: send 0.001000000000 XMR to 55GAd9ddNjKRAyi74PwhTKXkhyfDwvVmTGh7NTNHsaA2BfwShd5v8VHPWJaKuKNJYFJwvEx5nZ6fiMr4BC6UkoPzHjryVNK
```
and 
```
Funding required: send 0.00001500 BTC to tb1qx78xnxj4wxjgy28cvs6v6f7an9cgcxh8ps446r

or

Success: Funding required: send 0.00001500 BTC to tb1qx78xnxj4wxjgy28cvs6v6f7an9cgcxh8ps446r
```

**Comment by TheCharlatan** [comment]
Done in #334 , but moved out of the progress messages and moved into `needs-funding`
