### ISSUE TITLE
Make all cli messages serializable

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#285]
Output from the `peers`, `ls` and `info` commands are yaml serializable. Optimally, the `progress` messages should be too to make it easy for external applications to consume messages.

**Comment by h4sh3d** [comment]
Uhm, the way progress currently works it is not possible, but what kind of yaml output would you expect? In other words what would be the structure?

**Comment by TheCharlatan** [comment]
There's no point working on this now, it's going to take too much time. We will have to refactor the progress workflow, there's no really good reason why this shouldn't work. Lets get your proposal in and then we can think about how it can be yaml'ified.

**Comment by TheCharlatan** [comment]
The `needs-funding` messages can be made serializable once the amount serialization is available in monero-rs.

**Comment by TheCharlatan** [comment]
Only funding info remains. Funding info can be tackled once a new monero-rs version is released and bumped here with the new serde serialization on the amount type.
