### ISSUE TITLE
Connect a specific version of node to farcaster.dev for tests

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#287]
Website [farcaster.dev](https://farcaster.dev) can take a list of public offers, a special version of the node should be able to push offers there (the "maker" version) and the standard version should have a command to list them in cli.
- [ ] List available offers in cli
- [ ] Push new list of available offers in farcaster.dev from special node version

**Comment by h4sh3d** [comment]
As @zkao mentioned, if we are able to list offers from the cli there is no need to have a special node version, we can just script to list and update every x time.

I though about what the cli could look like and came up with this idea:
```
swap-cli ls <TYPE>
```
where `TYPE` is by defaults `swaps` with `ls swaps` being the current `ls` behavior and `ls offers` being the list of offers like:
```
---
- "Offer:Cke4ftrP5A71LQM2fvVdFMNR4gumFhEqm11111uMFq7cEPSbSQpvEiF11111TB9zym113GTvtvqfD1111114A4TULEXhypzp8nJ4WAGAZUdDkYai3i9KTgUHkGLs5zX3N1tA11111111111111111111111111111111111111111AfZ113XRBuJApN3x"
```

**Comment by zkao** [comment]
`ls` stands for `list swaps`

why reuse?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by h4sh3d** [comment]
I though `ls` was for `list`

**Comment by zkao** [comment]
maybe we should call it ListSwaps, and the abbreviation is ls, and the other ListOffers ?

**Comment by Lederstrumpf** [comment]
created https://github.com/farcaster-project/offer-refiller to address this. It's pushing public offers to the web frontend whenever the list of swaps offered is updated.
