### ISSUE TITLE
Print new heights in syncers on info level

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#305]
New height has been removed from info level in swapd, which IMO is a good thing, but we should add it in syncers (bitcoin, monero) so it gets printed 1x at each new height detected.

**Comment by zkao** [comment]
swapd needs to count down to provide user feedback about when to expect something to happen.

eg

btc locked, tx will be final in 2 blocks 
btc locked, tx will be final in 1 block
btc final

**Comment by zkao** [comment]
resolved
