### ISSUE TITLE
funding arrives after swap is already finished for alice

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#310]
14:21 <TheCharlatan/libera> just tested your alice shutdown, seems to work nicely :) . I wonder what we should do if the user funds too late, but I think this a recovery edge case we can tackle later.
14:27 <@zkao> too late like when, TheCharlatan/libera ?
14:27 <TheCharlatan/libera> like when bob already has sent cancel.
14:28 <TheCharlatan/libera> and alice's swapd has already shut down.

14:49 <@zkao> TheCharlatan/libera: when bob sends cancel, and only then alice funds, alice will end up on the refund path and sweep monero, that one i did test
14:54 <@zkao> oh, i guess only now i get what you said. alice shuts down first, and then the funding arrive

**Comment by zkao** [comment]
@TheCharlatan this is fixed, right?

**Comment by TheCharlatan** [comment]
Yes, and Iif not, it should be refined into a clearer issue.
