### ISSUE TITLE
Support tls monerod servers

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#396]

**Comment by LeoNero** [comment]
Can do after https://github.com/monero-ecosystem/monero-rpc-rs/pull/81 is merged

**Comment by TheCharlatan** [comment]
Tested.

**Comment by h4sh3d** [comment]
> Can do after [monero-rs/monero-rpc-rs#81](https://github.com/monero-rs/monero-rpc-rs/pull/81) is merged

This PR would allow client auth from server, regular tls (i.e. client <-> server as in HTTPS) can already be done with at least https://github.com/monero-rs/monero-rpc-rs/releases/tag/v0.3.2

@TheCharlatan  can you PR to change our defaults to use HTTPS?

**Comment by TheCharlatan** [comment]
I cannot, since we first need to discover a new set of stable public nodes that support https, or host them ourselves.

**Comment by h4sh3d** [comment]
Oh, I supposed rino had some...
