### ISSUE TITLE
Remove fee management from surface

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#403]
Fee will be managed by syncers. For now we remove the fee parameter, validation rules can be added later when their format is defined.

Closes #321.

**Comment by zkao** [comment]
my understanding is: participants need to agree on something similar to Aggressive or Conservative, as it was done in core, but I'd  guess it would be more useful to have something more granular such as mempool position.  @h4sh3d 

syncer can then provide the information about the current situation of the mempool, that can be used to accept or reject the trade @TheCharlatan 

e.g., i accept trading with people who create their transactions at position < 0.5 MvB (surface is 0 MvB) for values of up to 1 XMR

**Comment by TheCharlatan** [comment]
@h4sh3d what are the remaining problems with the fee estimation?

**Comment by h4sh3d** [comment]
## Fee recap
In core we define 2 types of possible fee: **fixed** and a **range**. Today we only test with fixed fee (`1 sat/vByte`). This fee rate is apply to all cooperative transactions: `buy`, `cancel`, and `refund` so one side do not arbitrarily dictate arbitrating fees (as `buy` and `cancel+refund` will always reduce the swap final amount this is an important aspect of the implementation).

## Minimal requirements
Overall the work needed to stabilize fee management for M.3 is (IMO):

- [ ] https://github.com/farcaster-project/farcaster-core/issues/117
- [ ] https://github.com/farcaster-project/farcaster-core/issues/312

## Next
To reintroduce flexible fee we need:

- A 'range' or something similar (can be the current implementation or something toward mempool position)
- Rework the fee priority concept according to the range concept
- Expose the priority in `farcasterd.toml` config and pass it to `swapd`

**Comment by h4sh3d** [comment]
Once https://github.com/farcaster-project/farcaster-core/pull/317 and core `0.6.2` is released all the upstream work will be complete and I'll open a fix for this one.
