### ISSUE TITLE
Not enough monero locked

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#405]
`[2022-02-21T18:30:18Z WARN farcaster_node::swapd::runtime] Not enough monero locked: expected 0.320196630000 XMR, found 0.235293730000 XMR`

not sure why, but not first time i see this, and below the offer

```
Want to buy 0.320196630000 XMR for 0.00004900 BTC at 6534.625102040816 XMR/BTC?

Carefully validate offer!

Trade counterparty: 026b9739e4610c2a7e8d585b5a9b81e243a7baabfacae421e47e7b038665ffebb1@159.100.242.14:9751

Network: Testnet
Blockchain: Bitcoin<SegwitV0>
- amount: 0.00004900 BTC
Blockchain: Monero
- amount: 0.320196630000 XMR
Timelocks
- cancel: 35 blocks
- punish: 100 blocks
Fee strategy: Fixed: 1 satoshi/vByte
Maker swap role: Alice
```

**Comment by Lederstrumpf** [comment]
haven't been able to reproduce on `main` after restarting services and @h4sh3d fixed auto-funding. I'll close this - reopen if it reoccurs.
