### ISSUE TITLE
swap failures on `688ad0598916305c0b2d08acef4045aaaba16f57`

### ISSUE THREAD

**Issue by Lederstrumpf** [farcaster-project/farcaster-node#462]
I'm getting ~2/3 failure cases on current main (`688ad0598916305c0b2d08acef4045aaaba16f57`) when doing 20 parallel swaps. I highly doubt it's related to their concurrency. Triaging by bisecting past revisions on `main` to see if this was introduced in a PR, or if it's an issue with our backend.

Attached are the logs for maker & takers
[logs_688ad0598916305c0b2d08acef4045aaaba16f57.tar.gz](https://github.com/farcaster-project/farcaster-node/files/8831467/logs_688ad0598916305c0b2d08acef4045aaaba16f57.tar.gz)

**Comment by TheCharlatan** [comment]
@Lederstrumpf  I think this can be closed, no?

**Comment by Lederstrumpf** [comment]
ah, yes, that's completely resolved, thanks!
