### ISSUE TITLE
Monero syncer address test fail

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#478]
The monero syncer address test failed on main, this looks linked to swaps that do not progress because the funding is not detected.

https://github.com/farcaster-project/farcaster-node/runs/6788515762?check_suite_focus=true#step:7:923

**Comment by h4sh3d** [comment]
I beleive this was related to monero lws, don't know if this is still valid? Ping @TheCharlatan

**Comment by TheCharlatan** [comment]
No, but it seems like it was a timing issue that I resolved somewhere along the way. I was not entirely sure if that was the fix, so I did not reference it here. I realize now, that was not all too clever. I'm for closing this though. We had probably upwards of 40 successful runs now without ever triggering this.
