### ISSUE TITLE
Do not log dependency logs by default

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#487]
Our current logs are polluted by debug logs from our dependencies. The logger we use, `env_logger`, supplies some fine-grained configuration for switching logging on for certain modules, as described [here](https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html). By setting for exmaple `RUST_LOG="info,farcasterd=debug,microservices=debug,checkpointd=debug,wallet=debug,syncerd=debug,swapd=debug,peerd=debug,farcaster_node=debug"` before running the binaries, only our own logs are printed. Investigate how this method for filtering logs can be used in the CI and deployed more generally when running our binaries.

**Comment by h4sh3d** [comment]
We can simplify the env variable to `RUST_LOG="info,farcaster_node=debug"`, this will bypass the `--verbosity` cli argument so we have to fix that also.

**Comment by TheCharlatan** [comment]
This done.
