### ISSUE TITLE
Handle Funding Recovery

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#493]
Once a funding transaction is received by Bob, he only locks after he has sent CoreArbitratingSetup to Alice and she has sent RefundProcedureSignatures back to him. 

In the case of double funding, or Alice never replying with `RefundProcedureSignatures`, Bob never enters the refund flow. For this reason, his funds are currently permanently stuck. This behavior has to be fixed before mainnet, because users could end up with permanently stuck funds that will be cumbersome to recover.

There are a few paths to resolving this:

1. Only watch for funding and present the funding address to the user after `RefundProcedureSignatures` have been received. This means presenting the funding address to the user and emitting `FundingInfo` after `RefundProcedureSignatures`. This ensure that on recovery, the normal `Fund` -> `Lock` -> `Refund` workflow is executed. However, this does not handle later transactions to the funding address, or underfunding.
2. Remove the funding transaction altogether and directly fund into Lock. This is potentially not possible, due to requirements on the input of the `Lock` transaction. It also means that the previously mentioned overfunding and underfunding are not handled.
3. Permanently store all funding private keys and allow users to sweep them by address. This handles all scenarios, but requires more permanent memory and requires the ability in the (syncer?) to sweep bitcoin from an address.

I am all for implementing points 1. and 3. If there are further alternatives, please let me know. In any case, at least reply with a thumbs up for going ahead with this and acknowledging the problematique.

**Comment by zkao** [comment]
> Permanently store all funding private keys and allow users to sweep them by address. This handles all scenarios, but requires more permanent memory and requires the ability in the (syncer?) to sweep bitcoin from an address.

On the long run, wouldn't it be simpler to use deterministic derivations of addresses?

**Comment by TheCharlatan** [comment]
> On the long run, wouldn't it be simpler to use deterministic derivations of addresses?

Yeah, an internal wallet would have been useful.

**Comment by h4sh3d** [comment]
All the keys should already be deterministic if we handle the offer id and properly integrate it into the KeyManager (currently a u32, it should be changed to integrate the whole id) as all keys use slip10 with deterministic indexes.

**Comment by TheCharlatan** [comment]
Eventually you'll end up integrating a key value store for addresses anyway, because of the gap limit, so I think just saving the funding addresses and their corresponding secret keys is fine for now.

**Comment by TheCharlatan** [comment]
Sweeping done in #499 , funding addresses persisted in #506
