### ISSUE TITLE
Flatten enum inner types

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#513]
`Request` enum implements `TypedEnum`, and can only have a single element in each of the enums variant. Because of that we created types that hold multiple elements, and these types become a single element inside an enum variant. 

However in other contexts we ended up applying this restriction that does not hold true. Syncer's `Event` enum being one example.

**Comment by TheCharlatan** [comment]
The typed enums are useful when consuming their specific type structs without having to re-match them.
