### ISSUE TITLE
Handle Overfunding / Underfunding

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#529]
I propose the following to handle overfunding / underfunding of both Bitcoin and Monero:

In case the Bitcoin funding transaction's amount does not match the requested amount, the swap should abort. Alice's swap will run indefinitely for now until the user manually cancels it. 

In case the Monero lock transaction's amount does not match the requested amount, the protocol should progress like a usual refund swap, with Alice  waiting for Bob to cancel and refund, and then sweeping the Monero. If Alice overfunds, she should not publish the buy transaction.

**Comment by zkao** [comment]
I'm not convinced about failing upon counterpartiy's overfunding. One should be thankful for the gift :D `Msg::ThankYou`

**Comment by TheCharlatan** [comment]
> I'm not convinced about failing upon counterpartiy's overfunding. One should be thankful for the gift :D Msg::ThankYou

Yeah, when Bob replies with the BuySignature for Alice, she should ignore it if she overfunded. Eventually the refund path must be triggered.

**Comment by TheCharlatan** [comment]
Closing with #530 and #531.
