### ISSUE TITLE
Petrinetify swapd's state machine

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#550]
right now there is too much dependence on the correct order of events

abstracting swapd further could generalize that, such as a set of events might call the same function, and in case all preconditions are met, that might lead to progression on the protocol run, right now typically its  a single event triggering progression. patching this would also would remove the race-conditions related to it.

**Comment by TheCharlatan** [comment]
#804 gets us close, but room for improvement will have to be sketched out anew again.
