### ISSUE TITLE
Databased crashes on start

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#576]
Start the node with empty `.farcaster` folder result in

```
[2022-07-19T13:54:41Z DEBUG databased] MSG RPC socket ipc://~/.farcaster/msg.rpc
[2022-07-19T13:54:41Z DEBUG databased] CTL RPC socket ipc://~/.farcaster/ctl.rpc
[2022-07-19T13:54:41Z DEBUG databased] Starting runtime ...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(2)', src/databased/runtime.rs:48:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think the crash comes from `lmdb::Environement::new()...open(&path)?;` where path points to folder `.farcaster`, what happen if there is no file to open?

**Comment by h4sh3d** [comment]
It should work with the `create_db` call, not sure it is that.

**Comment by TheCharlatan** [comment]
Can't reproduce. Maybe it is creating the db in an existing folder after all and it is trying to open an lmdb database that has a different and incompatible configuration? This might also explain the error code.
