### ISSUE TITLE
Event proposed API

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#677]
`new_name` <- `current_name`
`reply_ctl` <- `complete_ctl`: reply new msg to source and consume event
`reply_ctl_continue` <- `send_ctl`: reply new msg to source, only borrow event 
`forward_ctl`: forward current msg to new service and consume event
`forward_ctl_continue`: forward a copy of current message to new service, only borrow event
`send_ctl` <- `complete_ctl_service`: send to a new service a new message, consume the event
`send_ctl_continue` <-  `send_ctl_service`: send to a new service a new message, only borrow event

and the same for _p2p

**Comment by TheCharlatan** [comment]
This changed a bit now, so if this should still be discussed, please open a new issue.
