### ISSUE TITLE
walletd, grpcd and databased launching not using `runtime.spawning_services`

### ISSUE THREAD

**Issue by zkao** [farcaster-project/farcaster-node#689]
I also noticed now that the walletd, grpcd and databased launching are not using `runtime.spawning_services`

_Originally posted by @zkao in https://github.com/farcaster-project/farcaster-node/issues/670#issuecomment-1223854206_

**Comment by TheCharlatan** [comment]
As of #693 we now track online services (including syncers, database, peer, and wallet).
