### ISSUE TITLE
Prepare buses refactor

### ISSUE THREAD

**Issue by h4sh3d** [farcaster-project/farcaster-node#706]
Here is a picture of which microservice uses which buses to communicate with other services.

![Untitled scene](https://user-images.githubusercontent.com/7792896/187479911-9b74e0b0-8e45-4d36-80a6-8239e89e27b9.png)

- `cli` and `grpcd` use the RPC bus to query other services and receive responses
- `farcasterd` is connected to everything
- `peerd` receive and transfer protocol messages on the MSG bus, receive command from `farcasterd` or other services on the CTL bus and listen on RPC bus to `cli` and `grpcd` queries
- `swapd` does the same as `peerd` plus the SYNC bus to receive `syncerd` events
- `walletd` is not directly connected to RPC bus
- `syncerd` only needs CTL to be commanded and SYNC to send events
- `databased` only needs CTL and RPC

**Comment by TheCharlatan** [comment]
Thank you for sketching this so nicely. I've been re-thinking the bus layout again. In my mind, the cli and grpcd (or clients) should have access to the ctl bus as well. In general they are capable of issuing two different kinds of requests. One that triggers a state transition, and one that is purely informational. 

For example the cli can issue things like `info` and `progress` that just read state and don't manipulate anything, while calls like `take` `restore` etc. trigger a long chain of requests and state changes. I therefore suggest to rename the `Rpc` bus to `Info` bus. and give the cli and grpcd access to the `Ctl` bus as well.

This would also makes handling requests manipulating state easier to follow and read.

**Comment by h4sh3d** [comment]
New version of the diagram, also see #707 

![node-buses](https://user-images.githubusercontent.com/7792896/193844448-94d36989-0e5d-4a24-be8c-e8a41000e2d6.png)
