### ISSUE TITLE
Health-Check: Add network arguments to check

### ISSUE THREAD

**Issue by TheCharlatan** [farcaster-project/farcaster-node#801]
Provide an optional arg to health-check to filter by network, such as health-check mainnet (or health-check -n mainnet to maintain the same structure as make). It's only a minor nuisance though to see errors being thrown for networks you're not interested in, so it would be a low priority enhancement at best.

There was a monero-wallet-rpc that was really slow for some reason. The health check stalled for over 90 seconds multiple times then before returning connection error: Connection reset by peer (os error 104). Issue disappeared when I restarted monero-wallet-rpc.

Suggested by @Lederstrumpf

**Comment by TheCharlatan** [comment]
@Lederstrumpf is there a possibility that the monero wallet rpc was occupied by another RPC call in the meantime?

**Comment by Lederstrumpf** [comment]
> @Lederstrumpf is there a possibility that the monero wallet rpc was occupied by another RPC call in the meantime?

ah yes, good catch: I did the health check while running a swap.
