### ISSUE TITLE
wiki mixup

### ISSUE THREAD

**Issue by Gingeropolous** [farcaster-project/farcaster-node#939]
i couldn't find how to make a PR to fix this

but in the wiki, there's this

"...can run (we are assuming a testnet swap)

monero-wallet-rpc --stagenet --rpc-bind-port 38083\ "

it says testnet, but then it uses monero stagenet....  i guess you mean bitcoin testnet?

**Comment by h4sh3d** [comment]
Thanks, yes the sentence is a bit misleading, we talk about bitcoin testnet <> monero stagenet swap.

The wiki is synced with the docs/ folder, you can open a PR that modifies the file there and it should be automatically applied when merged.

**Comment by TheCharlatan** [comment]
This is done now.
